# Generated by Django 4.0.5 on 2022-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
